import { jsPDF } from "jspdf";
import { ExtractedContent } from "../types";

export const generatePdf = (data: ExtractedContent) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 25;
  const maxLineWidth = pageWidth - margin * 2;

  let y = margin;

  // Header / Branding
  doc.setFont("times", "bold");
  doc.setFontSize(10);
  doc.setTextColor(150);
  doc.text("ARTICLE READER ARCHIVE", margin, y);
  doc.text(new Date().toLocaleDateString(), pageWidth - margin, y, { align: "right" });
  y += 15;

  // Title
  doc.setFont("times", "bold");
  doc.setFontSize(24);
  doc.setTextColor(0);
  const titleLines = doc.splitTextToSize(data.title, maxLineWidth);
  doc.text(titleLines, margin, y);
  y += titleLines.length * 10 + 5;

  // Author Byline
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  doc.setTextColor(80);
  doc.text(`By ${data.author}`, margin, y);
  y += 15;

  // Separator
  doc.setDrawColor(200);
  doc.setLineWidth(0.5);
  doc.line(margin, y, pageWidth - margin, y);
  y += 15;

  // Abstract / Summary
  doc.setFont("times", "italic");
  doc.setFontSize(12);
  doc.setTextColor(40);
  const summaryPrefix = "Abstract: ";
  const summaryLines = doc.splitTextToSize(summaryPrefix + data.summary, maxLineWidth);
  doc.text(summaryLines, margin, y);
  y += summaryLines.length * 7 + 15;

  // Main Content
  doc.setFont("times", "normal");
  doc.setFontSize(12);
  doc.setTextColor(0);
  
  // Clean markdown for PDF
  const cleanContent = data.content
    .replace(/\*\*/g, "")
    .replace(/##/g, "")
    .replace(/\[.*?\]\(.*?\)/g, "");

  const contentLines = doc.splitTextToSize(cleanContent, maxLineWidth);
  
  // Pagination & Content Loop
  contentLines.forEach((line: string) => {
    if (y > pageHeight - margin) {
      doc.addPage();
      y = margin;
      // Header on new pages
      doc.setFont("times", "normal");
      doc.setFontSize(9);
      doc.setTextColor(150);
      doc.text(`${data.title} - Page ${doc.getNumberOfPages()}`, margin, y);
      y += 15;
      
      doc.setFont("times", "normal");
      doc.setFontSize(12);
      doc.setTextColor(0);
    }
    doc.text(line, margin, y);
    y += 7; // Line height
  });

  // Footer
  const footerY = pageHeight - 15;
  doc.setFontSize(9);
  doc.setTextColor(150);
  doc.text("Generated by Article Reader", pageWidth / 2, footerY, { align: "center" });

  doc.save(`${data.title.slice(0, 30).trim().replace(/[^a-z0-9]/gi, '_')}.pdf`);
};